SET PYTHON_VERSION={PYTHON_VERSION}
SET DELVE_HOME=%~dp0
SET PATH=%DELVE_HOME%;%PATH%
SET PATH=%DELVE_HOME%\bin;%PATH%
SET PATH=%DELVE_HOME%\python\%PYTHON_VERSION%;%PATH%
SET PATH=%DELVE_HOME%\python\%PYTHON_VERSION%\Scripts;%PATH%
SET PATH=%DELVE_HOME%\python\%PYTHON_VERSION%\Library\bin;%PATH%
