SET PYTHON_VERSION={PYTHON_VERSION}
SET FLASHLIGHT_HOME=%~dp0
SET PATH=%FLASHLIGHT_HOME%;%PATH%
SET PATH=%FLASHLIGHT_HOME%\bin;%PATH%
SET PATH=%FLASHLIGHT_HOME%\python\%PYTHON_VERSION%;%PATH%
SET PATH=%FLASHLIGHT_HOME%\python\%PYTHON_VERSION%\Scripts;%PATH%
SET PATH=%FLASHLIGHT_HOME%\python\%PYTHON_VERSION%\Library\bin;%PATH%
