# Generated by Django 5.1.6 on 2025-02-28 15:22

import events.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_query_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='modified',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=events.models.generate_uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='globalcontext',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='localcontext',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='query',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
